version: '2'

services:
  website:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - '.:/isserviceup'

  redis:
    image: redis
    command: redis-server --requirepass devpassword
    volumes:
     - 'redis:/var/lib/redis/data'

volumes:
  redis: