version: '2'

services:
  website:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - '.:/isserviceup'
    command: gunicorn -c "isserviceup/config/gunicorn.py" isserviceup.app:app --reload

  redis:
    image: redis
    command: redis-server --requirepass devpassword
    volumes:
     - 'redis:/var/lib/redis/data'

  celery:
    build: .
    command: celery worker -B -l info -A isserviceup.celeryapp.app
    volumes:
      - '.:/isserviceup'

volumes:
  redis: